title: Generador de Google Docs desde SpreadSheets
author: Luighi Viton-Zorrilla
email: lv@luighiviton.com
description: >- # this means to ignore newlines until "baseurl:"
  Esta página aloja la descripción del proyecto para la generación de Google Docs
  a partir de Google SpreadSheets, tomando en cuenta la estructura del documento.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: LuighiVZ
github_username:  LuighiV

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
    -
     scope:
         path: ""
     values:
         lang: es
         base-url: "/"
    -
     scope:
         path: en
     values:
         header_title: Google Docs generator from SpreadSheets
         lang: en
         base-url: "/en/"
